<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>
    <ItemGroup>
        <None Update="Migrations\*.sql" CopyToOutputDirectory="PreserveNewest" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Microsoft.Data.Sqlite" />
        <PackageReference Include="Npgsql" />
    </ItemGroup>
    <ItemGroup>
        <InternalsVisibleTo Include="Capacitor.Server.Data.Tests.Unit" />
        <InternalsVisibleTo Include="Capacitor.Server.Ingest" />
        <InternalsVisibleTo Include="Capacitor.Server.Analytics" />
        <InternalsVisibleTo Include="Capacitor.Server.Api" />
    </ItemGroup>
</Project>
